#import "NSXMLElementAdditions.h"

#import "XMPPStream.h"
#import "XMPPClient.h"
#import "XMPPJID.h"
#import "XMPPUser.h"
#import "XMPPResource.h"
#import "XMPPIQ.h"
#import "XMPPMessage.h"
#import "XMPPPresence.h"