# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'XMPPFrameworkTests' do

  pod "XMPPFramework", :path => "../../"
  pod 'KissXML/SwiftNSXML', :git => 'https://github.com/robbiehanson/KissXML.git', :commit => '749f4392dae83bc8feb12f402735513eb4fd7139'

end
